Shop/Areas/admin/Controllers/LevelController.cs
using Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.admin.Controllers
{
    public class LevelController : BaseController
    {
        // GET: admin/Size
        
        public ActionResult Index()
        {
            var list_size = new DAL_Level().getDanhSach();
            return View(list_size);
        }




        // kiểm tra Size tồn tại trong sql khi insert
        // GET: admin/Size/ValidateInsert
        public JsonResult ValidateInsert(FormCollection collection)
        {
            var key = collection["key"];
            var value = collection["value"];

            var result = new DAL_Level().ValidateInsertLevel(key, value);
            return Json(new
            {
                status = result
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ValidateEdit(int id, FormCollection collection)
        {
            var key = collection["key"];
            var value = collection["value"];

            var result = new DAL_Level().ValidateUpdateLevel(id, key, value);
            return Json(new
            {
                status = result
            }, JsonRequestBehavior.AllowGet);
        }


        // POST: admin/Size/Create
        [HttpPost]
        public JsonResult Create(FormCollection collection)
        {
            var ten = collection["tenSize"];
            var slug = collection["Slug"];
            var mota = collection["MoTa"];
            var db = new DAL_Level();
            var result = db.insertSize(ten, slug, mota);
            if (result)
            {
                return Json(new
                {
                    text = "Thêm thành công !!!",
                    status = "success"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    status = "error",
                    text = "Không thể thêm Size !!!"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: admin/Size/Edit/5
        public JsonResult Edit(int id)
        {
            var color = new DAL_Level().returnSize(id);
            return Json(new
            {
                value = color
            }, JsonRequestBehavior.AllowGet);
        }

        // POST: admin/Size/Edit/5
        [HttpPost]
        public JsonResult Edit(int id, FormCollection collection)
        {
            var ten = collection["tenSize"];
            var slug = collection["Slug"];
            var mota = collection["MoTa"];
            var db = new DAL_Level();
            var result = db.editSize(id, ten, slug, mota);
            if (result)
            {
                return Json(new
                {
                    text = "Sửa thành công !!!",
                    status = "success"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    status = "error",
                    text = "Không thể sửa Level !!!"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: admin/Size/Delete/5
        public JsonResult Delete(int id)
        {
            var result = new DAL_Level().deleteLevel(id);

            return Json(new
            {
                status = (result) ? "success" : "error",
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChangeStatus(int id)
        {
            var result = new DAL_Level().ChangeStatus(id);
            return Json(new
            {
                status = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

Shop/Areas/admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Areas.admin.Data;
using Models.EntityFramework;
using Models.DAL;
using Shop.Session;


namespace Shop.Areas.admin.Controllers
{
    public class LoginController : Controller
    {
        public AplicationDBContext context { set; get; }
        public LoginController()
        {
            this.context = new AplicationDBContext();
        }
        // GET: admin/Login
        public ActionResult Index()
        {
            return View();
        }

        /// 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin userLogin)
        {
            if (ModelState.IsValid)
            {
                var dal = new DAL_Users();
                userLogin.MatKhau = MaHoaMD5.GetHash(userLogin.MatKhau);
                var user = dal.getAcountEmail(userLogin.TaiKhoan);
                if (user != null && user.TRANG_THAI == true)
                {
                    if (user.MAT_KHAU == userLogin.MatKhau)
                    {
                        var userSession = new UserSession();
                        userSession.UserName = user.HO_TEN;
                        userSession.UserID = user.ID;
                        userSession.image = user.LINK_ANH;
                        Session.Add(CommonConstants.USER_SESSION, userSession);
                        return RedirectToAction("Index", "TrangChu");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Mật khẩu không đúng!");
                    }
                }

                else
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại!");
                }
                /* else if (result == -2)
                 {
                     ModelState.AddModelError("", "Tài khoản đang bị khóa!");
                 }*/
            }

            return View("Index");

        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Remove(CommonConstants.USER_SESSION);
            return RedirectToAction("Index");
        }
    }
}

Shop/Areas/admin/Controllers/ThongKeController.cs
using Models.DAL;
using Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;



namespace Shop.Areas.admin.Controllers
{
    public class ThongKeController : Controller
    {
        private AplicationDBContext db = new AplicationDBContext();

        // GET: admin/ThongKe       

        public ActionResult Index2()
        {
            return View();
        }
        public ActionResult Index3()
        {
            return View();
        }


    }
}

Shop/Areas/admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.EntityFramework;
using Shop.Data;
using Models.DAL;
using PagedList;
using System.IO;
using Shop.Areas.admin.Data;

namespace Shop.Areas.admin.Controllers
{
    public class UsersController : BaseController
    {
        private QuanLyJobDbContext db = new QuanLyJobDbContext();

        // GET: admin/Users
        private DAL_Users dalUsers { get; set; }
        public UsersController()
        {
            this.dalUsers = new DAL_Users();
        }
        public ActionResult Index(int? page)
        {
            int pagenumber = (page ?? 1) - 1;
            int totalCount = 0;
            var arrUsers = this.dalUsers.GetPageUsers(pagenumber, 10, out totalCount);
            IPagedList<ACOUNT> pageOrders = new StaticPagedList<ACOUNT>(arrUsers, pagenumber + 1, 10, totalCount);
            return View(pageOrders);
        }

        // GET: admin/Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACOUNT aCOUNT = db.ACOUNTs.Find(id);
            if (aCOUNT == null)
            {
                return HttpNotFound();
            }
            return View(aCOUNT);
        }

        // GET: admin/Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MAT_KHAU, EMAIL,HO_TEN,PHONE,DIA_CHI")] ACOUNT aCOUNT)
        {
            try
            {
                aCOUNT.TRANG_THAI = Request.Form["HienThi"].Contains("true") ? true : false;
                aCOUNT.IS_REMOVE = false;
                var sql = "Select * from ACOUNT where EMAIL = N'" + aCOUNT.EMAIL + "';";
                var checksdt = this.dalUsers.sqlQueryFristOrDefault("Select * from ACOUNT where PHONE = N'" + aCOUNT.PHONE + "';");
                var checkemail = this.dalUsers.sqlQueryFristOrDefault(sql);
                if (ModelState.IsValid)
                {
                    if (Request.Files.Get("images").ContentLength == 0)
                    {
                        ViewBag.Err = "Images không được để trống !!!";
                        return View(aCOUNT);
                    }
                    
                    else
                    {
                        aCOUNT.LINK_ANH = SaveUploadImage(Request.Files.Get("images"));
                    }

                    if (aCOUNT.MAT_KHAU == null)
                    {
                        ViewBag.Err = "Mật khẩu không được để trống !!!";
                        return View(aCOUNT);
                    }

                    if (aCOUNT.MAT_KHAU.Length < 6 || aCOUNT.MAT_KHAU.Length >100)
                    {
                        ViewBag.Err = "Mật khẩu có độ dài từ 6 đến 100 ký tự !!!";
                        return View(aCOUNT);
                    }

                    if (checksdt)
                    {
                        ViewBag.Err = "Số điện thoại đã tồn tại !!!";
                        return View(aCOUNT);
                    }
                    if (checkemail)
                    {
                        ViewBag.Err = "Email đã tồn tại !!!";
                        return View(aCOUNT);
                    }
                    aCOUNT.MAT_KHAU = MaHoaMD5.GetHash(aCOUNT.MAT_KHAU);
                    if (!this.dalUsers.InsertUsers(aCOUNT))
                    {
                        ViewBag.Err = "Lỗi không thể chèn tài khoản !!!";
                        return View(aCOUNT);
                    }
                    else
                    {
                        ViewBag.Success = "Chèn Thành Công !!!";
                        return RedirectToAction("Index");
                    }


                }
                // TODO: Add insert logic here

                return View(aCOUNT);

            }
            catch
            {
                return View(aCOUNT);
            }
        }

        private string SaveUploadImage(HttpPostedFileBase file)
        {
            var str_file = "";
            Random random = new Random();
            if (file != null && file.ContentLength > 0)
            {
                //Định nghĩa đường dẫn lưu file trên server
                var ServerSavePath = Path.Combine(Server.MapPath("~/UploadFileImage/images/") + file.FileName);
                string newFileName = file.FileName;
                //lấy đường dẫn lưu file sau khi kiểm tra tên file trên server có tồn tại hay không
                while (System.IO.File.Exists(ServerSavePath) == true)
                {
                    string filename = Path.GetFileNameWithoutExtension(newFileName);
                    string extension = Path.GetExtension(newFileName);
                    newFileName = filename + "_" + random.Next(1, 1000) + extension;
                    ServerSavePath = Path.Combine(Server.MapPath("~/UploadFileImage/images/") + newFileName);
                }
                //Lưu hình ảnh Resize từ file sử dụng file.InputStream
                file.SaveAs(ServerSavePath);

                str_file = "/UploadFileImage/images/" + newFileName;
            }
            return str_file;// trả về đường dẫn file trong thư mục
        }

        private void DropFileImages(string strFile)
        {
            var file = Server.MapPath(strFile);
            System.IO.File.Delete(file);
        }

        // GET: admin/Users/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ACOUNT aCOUNT = this.dalUsers.getUser(id);
            if (aCOUNT == null)
            {
                return HttpNotFound();
            }
            return View(aCOUNT);
        }

        // POST: admin/Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID ,EMAIL ,DIA_CHI,HO_TEN,PHONE")] ACOUNT aCOUNT)
        {
            try
            {
                aCOUNT.TRANG_THAI = Request.Form["HienThi"].Contains("true") ? true : false;
                var sql = "Select * from ACOUNT where ID !='"+aCOUNT.ID+"' AND EMAIL = N'" + aCOUNT.EMAIL + "';";
                var checksdt = this.dalUsers.sqlQueryFristOrDefault("Select * from ACOUNT where ID !='" + aCOUNT.ID + "' AND PHONE = N'" + aCOUNT.PHONE + "';");
                var checkemail = this.dalUsers.sqlQueryFristOrDefault(sql);
                if(Request["password"] != "")
                {
                    aCOUNT.MAT_KHAU = MaHoaMD5.GetHash(Request["password"]);
                }
                if (ModelState.IsValid && checkemail == false)
                {
                    var str_file  = this.dalUsers.getUser(aCOUNT.ID).LINK_ANH;
                    if (Request.Files.Get("images").ContentLength == 0)
                    {
                        aCOUNT.LINK_ANH = str_file;
                    }
                    else
                    {
                        aCOUNT.LINK_ANH = SaveUploadImage(Request.Files.Get("images"));
                    }
                    if (checksdt)
                    {
                        ViewBag.Err = "Số điện thoại đã tồn tại !!!";
                        if(aCOUNT.LINK_ANH != str_file) { DropFileImages(aCOUNT.LINK_ANH); }
                        return View(aCOUNT);
                    }
                    if (checkemail)
                    {
                        ViewBag.Err = "Email đã tồn tại !!!";
                        if (aCOUNT.LINK_ANH != str_file) { DropFileImages(aCOUNT.LINK_ANH); }
                        return View(aCOUNT);
                    }
                    
                    if (!this.dalUsers.EditUsers(aCOUNT.ID , aCOUNT))
                    {
                        ViewBag.Err = "Lỗi không thể sửa tài khoản !!!";
                        if (aCOUNT.LINK_ANH != str_file) { DropFileImages(aCOUNT.LINK_ANH); }
                        return View(aCOUNT);
                    }
                    else
                    {

                        ViewBag.Success = "Sửa Thành Công !!!";
                       
                        return RedirectToAction("Index");
                    }


                }
                // TODO: Add insert logic here

                return View(aCOUNT);

            }
            catch
            {
                return View(aCOUNT);
            }
        }

        // GET: admin/Users/Delete/5
        public ActionResult Delete(int id)
        {
            var result = new DAL_Users().DeleteUser(id);

            return Json(new
            {
                status = (result) ? "success" : "error",
            }, JsonRequestBehavior.AllowGet);
        }

       

        
    }
}

Shop/Areas/admin/Views/Shared/_Header.cshtml
@{
    Layout = null;

    var sessionUser = (ShopQuanAo.Session.UserSession)Session[ShopQuanAo.Session.CommonConstants.USER_SESSION];
}

<header class="header-desktop">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="header-wrap">
                <form class="form-header" method="get">
                    <input class="au-input au-input--xl" type="text" name="search" value="@ViewBag.Search" placeholder="Thông tin tìm kiếm" />
                    <button class="au-btn--submit" type="submit">
                        <i class="zmdi zmdi-search"></i>
                    </button>
                </form>
                <div class="header-button">
                   
                    <div class="account-wrap">
                        <div class="account-item clearfix js-item-menu">
                            <div class="image">
                                <img src="@sessionUser.image" alt="@sessionUser.UserName" />
                            </div>
                            <div class="content">
                                <a class="js-acc-btn" href="#">@sessionUser.UserName</a>
                            </div>
                            <div class="account-dropdown js-dropdown">
                                <div class="info clearfix">
                                    <div class="image">
                                        <a href="#">
                                            <img src="@sessionUser.image" alt="@sessionUser.UserName" />
                                        </a>
                                    </div>
                                    <div class="content">
                                        <h5 class="name">
                                            <a href="#">@sessionUser.UserName</a>
                                        </h5>
                                       
                                    </div>
                                </div>
                                <div class="account-dropdown__body">
                                    
                                    <div class="account-dropdown__item">
                                        <a href="@Url.Action("Edit" , "Users" , new { id = sessionUser.UserID })">
                                            <i class="zmdi zmdi-settings"></i>Setting
                                        </a>
                                    </div>
                                </div>
                                <div class="account-dropdown__footer">
                                    <a href="@Url.Action("Logout", "Login")">
                                        <i class="zmdi zmdi-power"></i>Logout
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

Shop/Areas/admin/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Minh Hiep">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- Fontfaces CSS-->
    <link href="~/Public/admin/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->@*
    <link href="~/Public/admin/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">*@
    <link href="~/Public/admin/vendor/bootstrap-5.0.0-dist/css/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- ~/Public/admin/vendor CSS-->
    <link href="~/Public/admin/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Public/admin/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @RenderSection("cssHeader", required: false)
    <!-- Main CSS-->
    <link href="~/Public/admin/css/theme.css" rel="stylesheet" media="all">
    <style>
        .position-absolute {
            position: absolute;
        }
    </style>
</head>

<body class="animsition">
    <div class="page-wrapper">
        @RenderPage("_SideBarMobile.cshtml")
        @RenderPage("_SideBar.cshtml")
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            @RenderPage("_Header.cshtml")
            <!-- HEADER DESKTOP-->
            <!-- MAIN CONTENT-->
            <div class="main-content">
                @RenderBody()
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <script>
        function onchange_ten(val) {
            var str = val.value;
            document.getElementById("SLUG").value = removeVietnameseTones(str);
        }
    </script>
    <!-- Jquery JS-->
    @* <script src="~/Public/admin/vendor/jquery-3.2.1.min.js"></script>*@
    <!-- Bootstrap JS-->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Public/admin/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Public/admin/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- ~/Public/admin/vendor JS       -->
    <script src="~/Public/admin/vendor/slick/slick.min.js"></script>
    <script src="~/Public/admin/vendor/wow/wow.min.js"></script>
    <script src="~/Public/admin/vendor/animsition/animsition.min.js"></script>
    <script src="~/Public/admin/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <script src="~/Public/admin/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Public/admin/vendor/counter-up/jquery.counterup.min.js"></script>
    <script src="~/Public/admin/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Public/admin/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Public/admin/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Public/admin/vendor/select2/select2.min.js"></script>

    <!-- Main JS-->
    <script src="~/Public/admin/js/main.js"></script>
    <script src="~/Public/admin/js/style.js"></script>

    @RenderSection("jsFooter", required: false)
</body>

</html>
<!-- end document-->

Shop/Areas/admin/Views/Shared/_SideBar.cshtml
@{
    Layout = null;

   
}

<!-- MENU SIDEBAR-->
<aside class="menu-sidebar d-none d-lg-block">
    <div class="logo">
        <a href="/admin">
            <img src="~/Public/admin/images/icon/logo.png" alt="Cool Admin" />
        </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
            <ul class="list-unstyled navbar__list">
                <li class=" active">
                    <a href="/admin">
                        <i class="fas fa-table"></i>Trang Chủ
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "LoaiNganhNghe")">
                        <i class="fas fa-chart-bar"></i>Quản Lý Loại Việc Làm
                    </a>
                </li>

                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-copy"></i>Quản Lý Việc Làm
                    </a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a href="@Url.Action("Index", "ViecLam")">Danh Sách Việc Làm</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Level")">Danh Sách Vị Trí công việc</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Create", "ViecLam")">Thêm Việc Làm</a>
                        </li>

                    </ul>
                </li>
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-copy"></i>Thống Kê
                    </a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a href="@Url.Action("Index2", "ThongKe")">Thống kê việc làm</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index3", "ThongKe")">Thống kê hồ sơ</a>
                        </li>
                    </ul>    
                <li>
                    <a href="@Url.Action("Index", "Slides")">
                        <i class="fas fa-calendar-alt"></i>Quản Lý Slide
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "TinTuc")">
                        <i class="fas fa-map-marker-alt"></i>Quản Lý Tin Tức
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index", "Users")">
                        <i class="fas fa-map-marker-alt"></i>Quản Lý Tài Khoản
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>
<!-- END MENU SIDEBAR-->

Shop/Areas/admin/Views/Shared/_SideBarMobile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<!-- HEADER MOBILE-->
<header class="header-mobile d-block d-lg-none">
    <div class="header-mobile__bar">
        <div class="container-fluid">
            <div class="header-mobile-inner">
                <a class="logo" href="index.html">
                    <img src="~/Public/admin/images/icon/logo.png" alt="CoolAdmin" />
                </a>
                <button class="hamburger hamburger--slider" type="button">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <nav class="navbar-mobile">
        <div class="container-fluid">
            <ul class="navbar-mobile__list list-unstyled">
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-tachometer-alt"></i>Dashboard
                    </a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a href="index.html">Dashboard 1</a>
                        </li>
                        <li>
                            <a href="index2.html">Dashboard 2</a>
                        </li>
                        <li>
                            <a href="index3.html">Dashboard 3</a>
                        </li>
                        <li>
                            <a href="index4.html">Dashboard 4</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="chart.html">
                        <i class="fas fa-chart-bar"></i>Charts
                    </a>
                </li>
                <li>
                    <a href="table.html">
                        <i class="fas fa-table"></i>Tables
                    </a>
                </li>
                <li>
                    <a href="form.html">
                        <i class="far fa-check-square"></i>Forms
                    </a>
                </li>
                <li>
                    <a href="calendar.html">
                        <i class="fas fa-calendar-alt"></i>Calendar
                    </a>
                </li>
                <li>
                    <a href="map.html">
                        <i class="fas fa-map-marker-alt"></i>Maps
                    </a>
                </li>
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-copy"></i>Pages
                    </a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a href="login.html">Login</a>
                        </li>
                        <li>
                            <a href="register.html">Register</a>
                        </li>
                        <li>
                            <a href="forget-pass.html">Forget Password</a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-desktop"></i>UI Elements
                    </a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a href="button.html">Button</a>
                        </li>
                        <li>
                            <a href="badge.html">Badges</a>
                        </li>
                        <li>
                            <a href="tab.html">Tabs</a>
                        </li>
                        <li>
                            <a href="card.html">Cards</a>
                        </li>
                        <li>
                            <a href="alert.html">Alerts</a>
                        </li>
                        <li>
                            <a href="progress-bar.html">Progress Bars</a>
                        </li>
                        <li>
                            <a href="modal.html">Modals</a>
                        </li>
                        <li>
                            <a href="switch.html">Switchs</a>
                        </li>
                        <li>
                            <a href="grid.html">Grids</a>
                        </li>
                        <li>
                            <a href="fontawesome.html">Fontawesome Icon</a>
                        </li>
                        <li>
                            <a href="typo.html">Typography</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!-- END HEADER MOBILE-->