Shop/Areas/admin/Controllers/TinTucController.cs
using Models.DAL;
using Models.EntityFramework;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Shop.Areas.admin.Controllers
{
    public class TinTucController : BaseController
    {
        // GET: admin/TinTuc
        private DAL_TinTuc dalTinTuc { get; set; }
        public TinTucController()
        {
            this.dalTinTuc = new DAL_TinTuc();
        }
        public ActionResult Index(int? page)
        {
            int pagenumber = (page ?? 1) - 1;
            int totalCount = 0;
            var listSlides = this.dalTinTuc.GetPageSlides(pagenumber, 10, out totalCount);
            IPagedList<BAI_VIET> pageOrders = new StaticPagedList<BAI_VIET>(listSlides, pagenumber + 1, 10, totalCount);
            return View(pageOrders);
        }

        // GET: admin/TinTuc/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


        private void DropFileImages(string strFile)
        {
            var file = Server.MapPath(strFile);
            System.IO.File.Delete(file);
        }

        private string SaveUploadImage(HttpPostedFileBase file)
        {
            var str_file = "";
            Random random = new Random();
            if (file != null && file.ContentLength > 0)
            {
                //Định nghĩa đường dẫn lưu file trên server
                var ServerSavePath = Path.Combine(Server.MapPath("~/UploadFileImage/images/") + file.FileName);
                string newFileName = file.FileName;
                //lấy đường dẫn lưu file sau khi kiểm tra tên file trên server có tồn tại hay không
                while (System.IO.File.Exists(ServerSavePath) == true)
                {
                    string filename = Path.GetFileNameWithoutExtension(newFileName);
                    string extension = Path.GetExtension(newFileName);
                    newFileName = filename + "_" + random.Next(1, 1000) + extension;
                    ServerSavePath = Path.Combine(Server.MapPath("~/UploadFileImage/images/") + newFileName);
                }
                //Lưu hình ảnh Resize từ file sử dụng file.InputStream
                file.SaveAs(ServerSavePath);

                str_file = "/UploadFileImage/images/" + newFileName;
            }
            return str_file;// trả về đường dẫn file trong thư mục
        }

        // GET: admin/TinTuc/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "SLUG,TIEU_DE,MO_TA,NOI_DUNG ")] BAI_VIET tintuc)
        {


            tintuc.NOI_BAT = Request.Form["NoiBat"].Contains("true") ? true : false ;
            tintuc.TRANG_THAI = Request.Form["HienThi"].Contains("true") ? true : false;
            var sql = "SELECT * FROM BAI_VIET WHERE SLUG = '"+tintuc.SLUG+"';";     
            if (ModelState.IsValid)
            {
                if (Request.Files.Get("images").ContentLength == 0)
                {
                    ViewBag.Err = "Images không được để trống !!!";
                    return View(tintuc);
                }
                else
                {
                    tintuc.IMAGES = SaveUploadImage(Request.Files.Get("images"));
                }

                var check = this.dalTinTuc.sqlQueryFristOrDefault(sql);
                if (check)
                {
                    ViewBag.Err = "Tiêu đề tin tức đã tồn tại !!!";
                    this.DropFileImages(tintuc.IMAGES);
                    return View(tintuc);
                }
                else
                {
                    if (this.dalTinTuc.CreateTinTuc(tintuc)) {

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Err = "Không thể chèn tin tức  !!!";
                        this.DropFileImages(tintuc.IMAGES);
                        return View(tintuc);

                    }

                }
            }

            return View(tintuc);
        }

     
        // GET: admin/TinTuc/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BAI_VIET bAI_VIET = this.dalTinTuc.returnBaiViet(id);
            if (bAI_VIET == null)
            {
                return HttpNotFound();
            }
            return View(bAI_VIET);
        }

        // POST: admin/TinTuc/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "MA_BV,SLUG,TIEU_DE,MO_TA,NOI_DUNG ")] BAI_VIET tintuc)
        {

            try
            {

                tintuc.NOI_BAT = Request.Form["NoiBat"].Contains("true") ? true : false;
                tintuc.TRANG_THAI = Request.Form["HienThi"].Contains("true") ? true : false;

                var sql = "SELECT * FROM BAI_VIET WHERE MA_BV != '"+tintuc.MA_BV+"' AND SLUG = '" + tintuc.SLUG + "';";
                    if (ModelState.IsValid)
                    {
                        var old_img = this.dalTinTuc.returnBaiViet(tintuc.MA_BV).IMAGES;
                    if (Request.Files.Get("images").ContentLength == 0)
                        {
                        tintuc.IMAGES = old_img;
                        }
                        else
                        {
                            tintuc.IMAGES = SaveUploadImage(Request.Files.Get("images"));
                        }

                        var check = this.dalTinTuc.sqlQueryFristOrDefault(sql);
                        if (check)
                        {
                            ViewBag.Err = "Tiêu đề tin tức đã tồn tại !!!";
                            if (tintuc.IMAGES != old_img) { DropFileImages(tintuc.IMAGES); }
                            return View(tintuc);
                        }
                        else
                        {
                            if (this.dalTinTuc.EditTinTuc(tintuc.MA_BV ,tintuc))
                            {

                                return RedirectToAction("Index");
                            }
                            else
                            {
                                ViewBag.Err = "Không thể sửa tin tức  !!!";
                            if (tintuc.IMAGES != old_img) { DropFileImages(tintuc.IMAGES); }
                            return View(tintuc);

                            }

                        }
                    }

                    return View(tintuc);
                
            }
            catch
            {
                return View();
            }
        }

        // GET: admin/TinTuc/Delete/5
        public ActionResult Delete(int id)
        {
            var result = new DAL_TinTuc().DeleteSlide(id);

            return Json(new
            {
                status = (result) ? "success" : "error",
            }, JsonRequestBehavior.AllowGet);
        }

        // POST: admin/TinTuc/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shop/Areas/admin/Views/TinTuc/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@model Models.EntityFramework.BAI_VIET
@section jsFooter{

    <script src="~/Public/Plugins/ckeditor/ckeditor.js"></script>
    <script src="~/Public/Plugins/ckfinder/ckfinder.js"></script>

    <script src="~/Public/admin/js/tintuc.js"></script>
}

<div class="section__content section__content--p30 mt-3">
    <div class="container-fluid">
        <div class="row ml-0 mr-0">
            @using (Html.BeginForm("Create", "TinTuc", FormMethod.Post, new { @class = "w-100", @enctype = "multipart/form-data" }))
            {

                @Html.AntiForgeryToken()

                <div class="card w-100">
                    <div class="card-header d-flex pl-3 pr-3 justify-content-between align-items-center">
                        <h3><strong>Thêm </strong> Tin Tức</h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <p>
                            @Html.ActionLink("Danh Sách", "Index", null, new { @class = "btn btn-success" })

                        </p>
                    </div>
                    <div class="card-body card-block">
                        @if (ViewBag.Err != null)
                        {
                            <div class="alert alert-danger">
                                <strong>Error : !</strong> @ViewBag.Err
                            </div>
                        }
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Tiêu Đề :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.TIEU_DE, new { htmlAttributes = new { @class = "form-control", @onchange = "onchange_ten(this)" } })

                                @Html.ValidationMessageFor(model => model.TIEU_DE, "", new { @class = "help-block form-text text-danger" })


                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Slug :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.SLUG, new { htmlAttributes = new { @readonly = "readonly", @class = "slug form-control" } })
                                @Html.ValidationMessageFor(model => model.SLUG, "", new { @class = "help-block form-text text-danger" })
                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Ảnh Chính :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <div class="form-group ">
                                    <input type="file" name="images" id="images" class="file-upload-default-image" style="position: absolute ; visibility: hidden;">
                                    <div class="input-group col-xs-12">
                                        <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">

                                        <span class="input-group-append">
                                            <button class="file-upload-image btn btn-primary" type="button">Upload</button>
                                        </span>
                                    </div>
                                    <small class="validate validate-images text-danger form-text "></small>
                                    <div class="hien-thi-image-chinh" style="min-width: 400px; max-width:500px ; margin: 1rem auto;">

                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Mô Tả :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.TextAreaFor(model => model.MO_TA, new { @id = "mo-ta", @rows = "4", @class = "mo-ta form-control" })
                                @Html.ValidationMessageFor(model => model.MO_TA, "", new { @class = "help-block form-text text-danger" })

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Nội Dung :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.TextAreaFor(model => model.NOI_DUNG, new { @id = "noi-dung", @rows = "9", @class = "noi-dung form-control" })
                                @Html.ValidationMessageFor(model => model.NOI_DUNG, "", new { @class = "help-block form-text text-danger" })

                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Nổi Bật :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.CheckBox("NoiBat", false)
                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Hiển Thị :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.CheckBox("HienThi", false)
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Reset
                        </button>
                    </div>
                </div>
            }



        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Shop/Areas/admin/Views/TinTuc/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


@model Models.EntityFramework.BAI_VIET
@section jsFooter{

    <script src="~/Public/Plugins/ckeditor/ckeditor.js"></script>

    <script src="~/Public/admin/js/tintuc.js"></script>
}

<div class="section__content section__content--p30 mt-3">
    <div class="container-fluid">
        <div class="row ml-0 mr-0">
            @using (Html.BeginForm("Edit", "TinTuc", FormMethod.Post, new { @class = "w-100", @enctype = "multipart/form-data" }))
            {

                @Html.AntiForgeryToken()

                <div class="card w-100">
                    <div class="card-header d-flex pl-3 pr-3 justify-content-between align-items-center">
                        <h3><strong>Sửa </strong> Tin Tức</h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <p>
                            @Html.ActionLink("Danh Sách", "Index", null, new { @class = "btn btn-success" })

                        </p>
                    </div>
                    <div class="card-body card-block">
                        @if (ViewBag.Err != null)
                        {
                            <div class="alert alert-danger">
                                <strong>Error : !</strong> @ViewBag.Err
                            </div>
                        }
                        @Html.HiddenFor(model => model.MA_BV)
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Tiêu Đề :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.TIEU_DE, new { htmlAttributes = new { @class = "form-control", @onchange = "onchange_ten(this)" } })

                                @Html.ValidationMessageFor(model => model.TIEU_DE, "", new { @class = "help-block form-text text-danger" })


                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Slug :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.SLUG, new { htmlAttributes = new { @readonly = "readonly", @class = "slug form-control" } })
                                @Html.ValidationMessageFor(model => model.SLUG, "", new { @class = "help-block form-text text-danger" })
                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Ảnh Chính :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                <div class="form-group ">
                                    <input type="file" name="images" id="images" class="file-upload-default-image" style="position: absolute ; visibility: hidden;">
                                    <div class="input-group col-xs-12">
                                        <input type="text" class="form-control file-upload-info" disabled="" placeholder="Upload Image">

                                        <span class="input-group-append">
                                            <button class="file-upload-image btn btn-primary" type="button">Upload</button>
                                        </span>
                                    </div>
                                    <small class="validate validate-images text-danger form-text "></small>
                                    <div class="hien-thi-image-chinh" style="min-width: 400px; max-width:500px ; margin: 1rem auto;">
                                        <img src="@Model.IMAGES" alt="Alternate Text" />
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Mô Tả :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.TextAreaFor(model => model.MO_TA, new { @id = "mo-ta", @rows = "4", @class = "mo-ta form-control" })
                                @Html.ValidationMessageFor(model => model.MO_TA, "", new { @class = "help-block form-text text-danger" })

                            </div>
                        </div>

                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Nội Dung :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.TextAreaFor(model => model.NOI_DUNG, new { @id = "noi-dung", @rows = "9", @class = "noi-dung form-control" })
                                @Html.ValidationMessageFor(model => model.NOI_DUNG, "", new { @class = "help-block form-text text-danger" })

                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Nổi Bật :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.CheckBox("NoiBat", Model.NOI_BAT.Value)
                            </div>
                        </div>
                        <div class="row form-group mb-3">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Hiển Thị :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.CheckBox("HienThi", Model.TRANG_THAI.Value)
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Reset
                        </button>
                    </div>
                </div>
            }



        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Shop/Areas/admin/Views/TinTuc/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@model PagedList.IPagedList<Models.EntityFramework.BAI_VIET>

@using PagedList.Mvc;


@section jsFooter{
    <script>
        $(".btn-delete-tintuc").off("click").on("click", function (e) {
            e.preventDefault();
            var btn = $(this);
            var id = btn.data("id");
            console.log(id);
            Swal.fire({
                title: 'Delete',
                icon: 'error',
                showCancelButton: true,
                confirmButtonText: 'Có',
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    $.ajax({
                        url: '/admin/TinTuc/Delete/' + id,
                        dataType: 'json',
                        type: "get"
                    }).done(function (data) {
                        // If successful
                        if (data.status == "success") {
                            Swal.fire("", "", data.status);
                            var row = $(".table-lsp").children("tbody").find("tr#row_" + id);
                            row.remove();
                        } else {
                            Swal.fire("", "", data.status);
                        }
                    })
                }
            });
        });
    </script>

}
@section cssHeader{

    <style>
        ul.pagination {
            justify-content: center;
        }

            ul.pagination li {
                display: inline;
                background: #e9ecef;
            }

                ul.pagination li.active {
                    background: teal;
                    color: white;
                }

                ul.pagination li a {
                    color: black;
                    float: left;
                    padding: 8px 16px;
                    text-decoration: none;
                    font-size: 16px;
                    transition: background-color .3s;
                }

                    ul.pagination li a.active {
                        background: teal;
                        color: white;
                    }

                    ul.pagination li a:hover:not(.active) {
                        background-color: #ddd;
                    }
    </style>

}



<div class="d-flex pl-3 pr-3 justify-content-between align-items-center mb-3">
    <h3 class="">Danh Sách Loại Việc Làm</h3>

    <p>
        @Html.ActionLink("Thêm Mới", "Create", null, new { @class = "btn btn-success" })
    </p>
</div>
<div class="section__content section__content--p30">

    <div class="container-fluid">
        <div class="row m-t-3">
            <div class="col-md-12">
                <!-- DATA TABLE-->
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success">
                        <strong>Success : !</strong>@ViewBag.Success
                    </div>
                }

                <div class="table-responsive m-b-40" style=" position:relative;">
                    <table class="table table-borderless table-data3 ">

                        <thead>
                            <tr>
                                <th class="text-center" width="5%">ID</th>
                                <th class="text-center" width="25%">Tiêu Đề</th>
                                <th class="text-center" width="20%">Ảnh</th>
                                <th class="text-center" width="20%">Mô Tả</th>
                                <th class="text-center" width="10%">Ngày Tạo</th>
                                <th class="text-center" width="8%">Nổi Bật</th>
                                <th class="text-center" width="8%">Status</th>
                                <th class="text-center" width="5%"></th>
                            </tr>
                        </thead>
                        <tbody>


                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.MA_BV">
                                    <td align="center"> @Html.DisplayFor(modelItem => item.MA_BV)</td>
                                    <td> @Html.DisplayFor(modelItem => item.TIEU_DE)</td>
                                    <td align="center">
                                        <div class="images" style="max-width:100%;">
                                            <img src="@item.IMAGES" alt="" class="w-100" style="max-height:130px;" />
                                        </div>
                                    </td>
                                    <td> @Html.DisplayFor(modelItem => item.MO_TA)</td>
                                    <td align="center"> @Html.DisplayFor(modelItem => item.NGAY_DANG)</td>
                                    <td align="center" class="process">

                                        <span data-id="@item.MA_BV" class="badge badge-pill btn-active-lsp @((item.NOI_BAT == true)?"badge bg-success":"badge bg-danger")">
                                            <i class="fa  @((item.NOI_BAT == true)?"fa-eye":"fa-eye-slash")">@((item.NOI_BAT == true)? "  Active" : "  Die")</i>
                                        </span>


                                    </td>
                                    <td align="center" class="process">

                                        <span data-id="@item.MA_BV" class="badge badge-pill btn-active-lsp @((item.TRANG_THAI == true)?"badge bg-success":"badge bg-danger")">
                                            <i class="fa  @((item.TRANG_THAI == true)?"fa-eye":"fa-eye-slash")">@((item.TRANG_THAI == true)? "  Active" : "  Die")</i>
                                        </span>


                                    </td>
                                    <td align="center">
                                        <div class="table-data-feature">

                                            <a href="@Url.Action("Edit", "TinTuc", new { id = item.MA_BV })" class="btn item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                                <i class="zmdi zmdi-edit"></i>
                                            </a>

                                            <a class="btn item btn-delete-tintuc" data-toggle="tooltip" data-id="@item.MA_BV" data-placement="top" title="" data-original-title="Delete">
                                                <i class="zmdi zmdi-delete"></i>
                                            </a>

                                        </div>
                                    </td>
                                </tr>
                            }



                            <tr>
                                <td colspan="8" class="align-items-center">
                                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
                               {
                                   DisplayLinkToIndividualPages = true,
                                   DisplayPageCountAndCurrentLocation = false,
                                   MaximumPageNumbersToDisplay = 10,
                                   LiElementClasses = new string[] { "page-item" }
                               })
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- END DATA TABLE-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>