Shop/Areas/admin/Controllers/LoaiNganhNgheController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models.DAL;
using Models.EntityFramework;
using Shop.Areas.admin.Data;


namespace Shop.Areas.admin.Controllers
{
    public class LoaiNganhNgheController : BaseController
    {
        private AplicationDBContext db = new AplicationDBContext();

        // GET: admin/lOAI_NGANH_NGHE
        public ActionResult Index(int page = 1, string search = null)
        {
            var dalLSP = new DAL_LoaiNganhNghe();
            ViewBag.Search = search;
            var model = dalLSP.ListAllPaging(page, 5, search);
            return View(model);
        }

        // GET: admin/lOAI_NGANH_NGHE/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAI_NGANH_NGHE lOAI_NGANH_NGHE = db.LOAI_NGANH_NGHE.Find(id);
            if (lOAI_NGANH_NGHE == null)
            {
                return HttpNotFound();
            }
            return View(lOAI_NGANH_NGHE);
        }

        // GET: admin/lOAI_NGANH_NGHE/Create
        public ActionResult Create()
        {

            this.SetSelectOption();
            return View();
        }

        public void SetSelectOption(int? selected = null)
        {
            var ListSelectOption = new DeQuySelectOption().ListSelectOption().Where(c => c.IS_REMOVE == false).ToList();
            var lsp = new SelectOptionLoaiViecLam();
            lsp.ID_CHA = 0;
            lsp.TEN_LOAI_VL = " --- Không thuộc loại nào ---";
            ListSelectOption.Insert(0, lsp);
            ViewBag.MovieType = new SelectList(ListSelectOption, "ID_LOAI_VL", "TEN_LOAI_VL", selected);
        }

        // POST: admin/lOAI_NGANH_NGHE/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LOAI_NGANH_NGHE lOAI_NGANH_NGHE)
        {
            var DB = new DAL_LoaiNganhNghe();
            if (ModelState.IsValid)
            {
                var check = DB.Check_isset_danh_muc_insert(lOAI_NGANH_NGHE.SLUG);
                if (check)
                {
                    lOAI_NGANH_NGHE.IS_REMOVE = false;
                    bool insert = DB.insertLoaiViecLam(lOAI_NGANH_NGHE);
                    if (check)
                    {
                        ViewBag.Success = "Thêm Thành Công !!! ";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Err = "Không chèn được ";
                        SetSelectOption();
                        return View(lOAI_NGANH_NGHE);
                    }
                }
                else
                {
                    ViewBag.Err = "Loại ngành nghề đã tồn tại";
                    SetSelectOption();
                    return View(lOAI_NGANH_NGHE);
                }

            }
            SetSelectOption();
            return View(lOAI_NGANH_NGHE);
        }

        // GET: admin/lOAI_NGANH_NGHE/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            this.SetSelectOption(id);

            LOAI_NGANH_NGHE lOAI_NGANH_NGHE = db.LOAI_NGANH_NGHE.Find(id);

            if (lOAI_NGANH_NGHE == null)
            {
                return HttpNotFound();
            }
            return View(lOAI_NGANH_NGHE);
        }

        // POST: admin/lOAI_NGANH_NGHE/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LOAI_NGANH_NGHE lOAI_NGANH_NGHE)
        {
            if (ModelState.IsValid)
            {
                var DB = new DAL_LoaiNganhNghe();
                var check = DB.Check_isset_danh_muc_update(lOAI_NGANH_NGHE.ID_LOAI_VL, lOAI_NGANH_NGHE.SLUG);
                if (check)
                {
                    bool insert = DB.updateLoaiViecLam(lOAI_NGANH_NGHE.ID_LOAI_VL, lOAI_NGANH_NGHE);
                    if (insert)
                    {
                        ViewBag.Success = "Sửa Thành Công !!! ";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Err = "Không sửa được ";
                        SetSelectOption((int)lOAI_NGANH_NGHE.ID_CHA);
                        return View(lOAI_NGANH_NGHE);
                    }
                }
                else
                {
                    ViewBag.Err = "Loại sản phẩm đã tồn tại";
                    SetSelectOption((int)lOAI_NGANH_NGHE.ID_CHA);
                    return View(lOAI_NGANH_NGHE);
                }

                return RedirectToAction("Index");
            }
            SetSelectOption(lOAI_NGANH_NGHE.ID_CHA);
            return View(lOAI_NGANH_NGHE);
        }

        public JsonResult Delete(int id)
        {
            var result = new DAL_LoaiNganhNghe().DeleteLoaiViecLam(id);

            return Json(new
            {
                status = (result) ? "success" : "error",
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChangeStatus(int id)
        {
            var result = new DAL_LoaiNganhNghe().ChangeStatus(id);
            return Json(new
            {
                status = result
            });
        }


        // POST: admin/lOAI_NGANH_NGHE/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LOAI_NGANH_NGHE lOAI_NGANH_NGHE = db.LOAI_NGANH_NGHE.Find(id);
            db.LOAI_NGANH_NGHE.Remove(lOAI_NGANH_NGHE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shop/Areas/admin/Views/LoaiNganhNghe/Create.cshtml
@model Models.EntityFramework.LOAI_NGANH_NGHE

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}


<div class="section__content section__content--p30 mt-3">
    <div class="container-fluid">
        <div class="row ml-0 mr-0">
            @using (Html.BeginForm("Create", "LoaiViecLam", FormMethod.Post, new { @class = "w-100" }))
            {
                @Html.AntiForgeryToken()
                <div class="card w-100">
                    <div class="card-header d-flex pl-3 pr-3 justify-content-between align-items-center">
                        <h3><strong>Thêm </strong> Danh Mục Loại Ngành Nghề</h3>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <p>
                            @Html.ActionLink("Danh Sách", "Index", null, new { @class = "btn btn-success" })

                        </p>
                    </div>
                    <div class="card-body card-block">
                        @if (ViewBag.Err != null)
                        {
                            <div class="alert alert-danger">
                                <strong>Error : !</strong> @ViewBag.Err
                            </div>
                        }
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="text-input" class=" form-control-label">Tên Loại Ngành Nghề :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.TEN_LOAI_VL, new { htmlAttributes = new { @class = "form-control", @onchange = "onchange_ten(this)" } })

                                @Html.ValidationMessageFor(model => model.TEN_LOAI_VL, "", new { @class = "help-block form-text text-danger" })


                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="email-input" class=" form-control-label">Slug :</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.EditorFor(model => model.SLUG, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.SLUG, "", new { @class = "help-block form-text text-danger" })
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-3">
                                <label for="select" class=" form-control-label">Thuộc Loại Ngành Nghề</label>
                            </div>
                            <div class="col-12 col-md-9">
                                @Html.DropDownListFor(model => model.ID_CHA, new SelectList(ViewBag.MovieType, "Value", "Text"), new { @class = "form-control" })
                            </div>
                        </div>


                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-danger btn-sm">
                            <i class="fa fa-ban"></i> Reset
                        </button>
                    </div>
                </div>
            }

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Shop/Areas/admin/Views/LoaiNganhNghe/Details.cshtml
@model Models.EntityFramework.LOAI_NGANH_NGHE

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LOAI_SAN_PHAM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TEN_LOAI_SP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TEN_LOAI_SP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SLUG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SLUG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TRANG_THAI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TRANG_THAI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_CHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_CHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NGAY_TAO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NGAY_TAO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_LOAI_SP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Shop/Areas/admin/Views/LoaiNganhNghe/Edit.cshtml
@model Models.EntityFramework.LOAI_NGANH_NGHE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="section__content section__content--p30">
    <div class="container-fluid">
        <div class="row">
            @using (Html.BeginForm("Edit", "LoaiViecLam", FormMethod.Post, new { @class = "w-100" }))
            {
                @Html.AntiForgeryToken()
            <div class="card w-100">
                <div class="card-header d-flex pl-3 pr-3 justify-content-between align-items-center">
                    <h3><strong>Sửa </strong> Danh Mục Loại Việc Làm : @Model.ID_LOAI_VL </h3>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <p>
                        @Html.ActionLink("Danh Sách", "Index", null, new { @class = "btn btn-success" })

                    </p>
                    @Html.HiddenFor(model => model.ID_LOAI_VL)
                </div>
                
                <div class="card-body card-block">
                    @if (ViewBag.Err != null)
                    {
                        <div class="alert alert-danger">
                            <strong>Error : !</strong> @ViewBag.Err
                        </div>
                    }
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="text-input" class=" form-control-label">Tên Loại Việc Làm :</label>
                        </div>
                        <div class="col-12 col-md-9">
                            @Html.EditorFor(model => model.TEN_LOAI_VL, new { htmlAttributes = new { @class = "form-control", @onchange = "onchange_ten(this)" } })

                            @Html.ValidationMessageFor(model => model.TEN_LOAI_VL, "", new { @class = "help-block form-text text-danger" })


                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="email-input" class=" form-control-label">Slug :</label>
                        </div>
                        <div class="col-12 col-md-9">
                            @Html.EditorFor(model => model.SLUG, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.SLUG, "", new { @class = "help-block form-text text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="select" class=" form-control-label">Thuộc Loại Ngành Nghề</label>
                        </div>
                        <div class="col-12 col-md-9">
                            @Html.DropDownListFor(model => model.ID_CHA, new SelectList(ViewBag.MovieType, "Value", "Text"), new { @class = "form-control" })
                        </div>
                    </div>


                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Update
                    </button>
                    <button type="reset" class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </div>
            }

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Shop/Areas/admin/Views/LoaiNganhNghe/Index.cshtml
@model PagedList.IPagedList<Models.EntityFramework.LOAI_NGANH_NGHE>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
@section cssHeader{

    <style>
        ul.pagination {
            justify-content: center;
        }

            ul.pagination li {
                display: inline;
                background: #e9ecef;
            }

                ul.pagination li.active {
                    background: teal;
                    color: white;
                }

                ul.pagination li a {
                    color: black;
                    float: left;
                    padding: 8px 16px;
                    text-decoration: none;
                    font-size: 16px;
                    transition: background-color .3s;
                }

                    ul.pagination li a.active {
                        background: teal;
                        color: white;
                    }

                    ul.pagination li a:hover:not(.active) {
                        background-color: #ddd;
                    }
    </style>

}


<div class="d-flex pl-3 pr-3 justify-content-between align-items-center mb-3">
    <h3 class="">Danh Sách Loại Ngành Nghề Làm Việc</h3>

    <p>
        @Html.ActionLink("Thêm Mới", "Create", null, new { @class = "btn btn-success" })
    </p>
</div>
<div class="section__content section__content--p30">

    <div class="container-fluid">
        <div class="row m-t-3">
            <div class="col-md-12">
                <!-- DATA TABLE-->
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success">
                        <strong>Success : !</strong>@ViewBag.Success
                    </div>
                }

                <div class="table-responsive m-b-40" style=" position:relative;">
                    <table class="table table-borderless table-data3 table-lsp">

                        <thead>
                            <tr>
                                <th width="10%">ID</th>
                                <th>Tên Loại Ngành Nghề</th>
                                <th>Thuộc Loại Ngành Nghề</th>
                                <th>Status</th>
                                <th width="5%"></th>
                            </tr>
                        </thead>
                        <tbody>
                            

                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID_LOAI_VL">
                                    <td> @Html.DisplayFor(modelItem => item.ID_LOAI_VL)</td>
                                    <td> @Html.DisplayFor(modelItem => item.TEN_LOAI_VL)</td>
                                    <td> @(Model.SingleOrDefault(c=>c.ID_LOAI_VL == item.ID_CHA) != null ? Model.SingleOrDefault(c => c.ID_LOAI_VL == item.ID_CHA   ).TEN_LOAI_VL : "")</td>
                                    <td class="process">

                                        <span data-id="@item.ID_LOAI_VL" class="badge badge-pill btn-active-lsp @((item.TRANG_THAI == true)?"badge bg-success":"badge bg-danger")">
                                            <i class="fa  @((item.TRANG_THAI == true)?"fa-eye":"fa-eye-slash")">@((item.TRANG_THAI == true)? "  Active" : "  Die")</i>
                                        </span>


                                    </td>
                                    <td>
                                        <div class="table-data-feature">

                                            <a href="@Url.Action("Edit", "LoaiNganhNghe", new { id = item.ID_LOAI_VL })" class="btn item" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                                <i class="zmdi zmdi-edit"></i>
                                            </a>

                                            <a class="btn item btn-delete-lsp" data-toggle="tooltip" data-id="@item.ID_LOAI_VL" data-placement="top" title="" data-original-title="Delete">
                                                <i class="zmdi zmdi-delete"></i>
                                            </a>

                                        </div>
                                    </td>
                                </tr>       
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5" class="align-items-center">
                                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = @ViewBag.Search }), new PagedListRenderOptions
                               {
                                   DisplayLinkToIndividualPages = true,
                                   DisplayPageCountAndCurrentLocation = false,
                                   MaximumPageNumbersToDisplay = 10,
                                   LiElementClasses = new string[] { "page-item" }
                               })
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- END DATA TABLE-->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>